### ISSUE TITLE
cfg and weights file

### ISSUE THREAD

**Issue by Micky-123** [DoranLyong/yolov4-tiny-tflite-for-person-detection#1]
Hi @DoranLyong ,
Your work looks very interesting.
I would like to experiment with few images. Can you please point to the place where the darknet .cfg file and the weights are present.

Thanks

**Comment by DoranLyong** [comment]
Hi @Micky-123, you seem to want to know where the configurations are for ```Darknet``` setup. <br/>

I recommend referring to this [link](https://medium.com/analytics-vidhya/train-a-custom-yolov4-tiny-object-detector-using-google-colab-b58be08c9593#a70f), which I totally followed. The ```.cfg``` file is only for training, so it is not included in this repository. <br/> 

The weight file is located [here](https://github.com/DoranLyong/yolov4-tiny-tflite-for-person-detection/tree/main/checkpoints), which was converted from ```.weights``` to. This is because after training my ```darknet yolov4-tiny``` model, I employed it for ```tensorflow lite``` version. Check [this repository](https://github.com/hunglc007/tensorflow-yolov4-tflite).

**Comment by Micky-123** [comment]
Thanks @DoranLyong . 

I am looking for the Darknet weights and the darknet cfg file. You would have used to generate the TFLite model. Can you please point to that if you have them 

BTW - I am getting the following error while executing "python run_person_detector.py --image ./data/persons.jpg --score 0.75":
\yolov4-tiny-tflite-for-person-detection\core\utils.py", line 152, in draw_bbox
    for i in range(num_boxes):
TypeError: only integer scalar arrays can be converted to a scalar index
Did you come across this any time?

Thanks

**Comment by DoranLyong** [comment]
Hi, @Micky-123. I found out some code block makes wrong in building bounding boxes. <br/>
I'm gonna fix it soon.


I involved the link for both configuration setups: 
* [yolov4-tiny-custom.cfg](https://drive.google.com/file/d/1m5UpR1WJVMmTzyqdd03WSr8SHRfr649e/view?usp=sharing) 
* [yolov4-tiny-custom_last.weights](https://drive.google.com/file/d/1pL0z7E3-wyCjJ3fFkWyZYQSOdhPAW6FY/view?usp=sharing) 

You could employ them for your own model. <br/>

**Comment by Micky-123** [comment]
> Hi, @Micky-123. I found out some code block makes wrong in building bounding boxes.
> 
> I'm gonna fix it soon.
> 
> I involved the link for both configuration setups:
> 
> * [yolov4-tiny-custom.cfg](https://drive.google.com/file/d/1m5UpR1WJVMmTzyqdd03WSr8SHRfr649e/view?usp=sharing)
> * [yolov4-tiny-custom_last.weights](https://drive.google.com/file/d/1pL0z7E3-wyCjJ3fFkWyZYQSOdhPAW6FY/view?usp=sharing)
> 
> You could employ them for your own model.

Thanks @DoranLyong! Appreciate it. Looking forward for the bug fix.

**Comment by DoranLyong** [comment]
@Micky-123, I updated the training methods in [this repository](https://github.com/DoranLyong/Darknet-YOLOv4-Tensorflow_Lite-Tutorial) <br/> 

You could train your model with your custom person dataset, following the instructions :)

**Comment by Micky-123** [comment]
> @Micky-123, I updated the training methods in [this repository](https://github.com/DoranLyong/Darknet-YOLOv4-Tensorflow_Lite-Tutorial)
> 
> You could train your model with your custom person dataset, following the instructions :)

Thanks DoranLyong!
